# Generated by Django 4.1 on 2022-08-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watch_list", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Movies", new_name="Movie",),
    ]
